---
name: Docker Build and Push

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      packages: write

    steps:
      - name: ⤵️ Checkout repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🏗️ Set up Docker Buildx
        # yamllint disable-line rule:line-length
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: 🔑 Docker Login to Docker Hub Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔑 Docker Login to GHCR Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 🔑 Docker Login to local Forgejo Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: 1d.lol
          username: ${{ vars.LOCAL_PACKAGES_USERNAME }}
          password: ${{ secrets.LOCAL_PACKAGES_TOKEN }}

      - name: 💄 Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/mdns-repeater
            ghcr.io/${{ vars.GHCR_USERNAME }}/mdns-repeater
            1d.lol/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          # yamllint disable rule:line-length
          labels: |
            org.opencontainers.image.authors=Darell Tan, Alex van den Hoogen
            org.opencontainers.image.documentation=https://github.com/alex3305/mdns-repeater
            org.opencontainers.image.licenses=GPL-2.0-only
            org.opencontainers.image.source=https://github.com/alex3305/mdns-repeater
            org.opencontainers.image.url=https://github.com/alex3305/mdns-repeater
            org.opencontainers.image.vendor=Alex van den Hoogen
          # yamllint enable rule:line-length

      - name: 👷 Docker Build and push latest
        # yamllint disable-line rule:line-length
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
